---
Name: orderconfig
---
LeftAndMain:
  extra_requirements_css:
    - orders/css/admin.css

## Extensions
Controller:
  extensions:
    - OrdersControllerExtension
SiteConfig:
  extensions:
    - OrdersSiteConfigExtension
Member:
  extensions:
    - OrdersMemberExtension
Group:
  extensions:
    - OrdersGroupExtension
Order:
  extensions:
    - Payable
Payment:
  extensions:
    - OrdersPaymentExtension